name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Executar script
      run: |
        python app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Simular deploy
      run: echo "Deploy realizado com sucesso!"